In [3]:
pip install beautifulsoup4 lxml html5lib

Requirement already satisfied: beautifulsoup4 in d:\localdiskshort\venv\lib\site-packages (4.13.4)
Requirement already satisfied: lxml in d:\localdiskshort\venv\lib\site-packages (6.0.0)
Requirement already satisfied: html5lib in d:\localdiskshort\venv\lib\site-packages (1.1)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\localdiskshort\venv\lib\site-packages (from beautifulsoup4) (4.14.0)
Requirement already satisfied: soupsieve>1.2 in d:\localdiskshort\venv\lib\site-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: webencodings in d:\localdiskshort\venv\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in d:\localdiskshort\venv\lib\site-packages (from html5lib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 25.1.1 is available.
You should consider upgrading via the 'D:\localdiskshort\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [4]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in d:\localdiskshort\venv\lib\site-packages (4.13.4)
Requirement already satisfied: soupsieve>1.2 in d:\localdiskshort\venv\lib\site-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\localdiskshort\venv\lib\site-packages (from beautifulsoup4) (4.14.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 25.1.1 is available.
You should consider upgrading via the 'D:\localdiskshort\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [6]:
from bs4 import BeautifulSoup
import requests

In [7]:
url ="https://en.wikipedia.org/wiki/List_of_largest_companies_in_India"

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html.parser')

In [1]:
# print(soup)

In [8]:
soup.find('table')

<table class="wikitable sortable" style="text-align:right;">
<tbody><tr>
<th align="center">Rank
</th>
<th align="center">Forbes<br/> 2000 rank
</th>
<th align="center">Name
</th>
<th align="center">Headquarters
</th>
<th align="center">Revenue<br/>(billions US$)
</th>
<th align="center">Profit<br/>(billions US$)
</th>
<th align="center">Assets<br/>(billions US$)
</th>
<th align="center">Value<br/>(billions US$)
</th>
<th align="center">Industry
</th></tr>
<tr>
<td>1
</td>
<td>49
</td>
<td align="left"><a class="mw-redirect" href="/wiki/Reliance_Industries_Limited" title="Reliance Industries Limited">Reliance Industries Limited</a>
</td>
<td align="left">Mumbai
</td>
<td>108.8
</td>
<td>8.4
</td>
<td>210.5
</td>
<td>233.1
</td>
<td align="left"><a href="/wiki/Conglomerate_(company)" title="Conglomerate (company)">Conglomerate</a>
</td></tr>
<tr>
<td>2
</td>
<td>55
</td>
<td align="left"><a href="/wiki/State_Bank_of_India" title="State Bank of India">State Bank of India</a>
</td>
<td align="left">Mumbai
</td>
<td>71.8
</td>
<td>8.1
</td>
<td>807.4
</td>
<td>87.6
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>3
</td>
<td>65
</td>
<td align="left"><a href="/wiki/HDFC_Bank" title="HDFC Bank">HDFC Bank</a>
</td>
<td align="left">Mumbai
</td>
<td>49.3
</td>
<td>7.7
</td>
<td>483.2
</td>
<td>133.6
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>4
</td>
<td>70
</td>
<td align="left"><a href="/wiki/Life_Insurance_Corporation" title="Life Insurance Corporation">Life Insurance Corporation</a>
</td>
<td align="left">New Delhi
</td>
<td>98.0
</td>
<td>4.9
</td>
<td>561.4
</td>
<td>73.6
</td>
<td align="left">Insurance
</td></tr>
<tr>
<td>5
</td>
<td>142
</td>
<td align="left"><a href="/wiki/ICICI_Bank" title="ICICI Bank">ICICI Bank</a>
</td>
<td align="left">Mumbai
</td>
<td>28.5
</td>
<td>5.3
</td>
<td>283.5
</td>
<td>95.3
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>6
</td>
<td>207
</td>
<td align="left"><a href="/wiki/Oil_and_Natural_Gas_Corporation" title="Oil and Natural Gas Corporation">Oil and Natural Gas Corporation</a>
</td>
<td align="left">New Delhi
</td>
<td>77.5
</td>
<td>5.1
</td>
<td>80.6
</td>
<td>41.9
</td>
<td align="left">Oil and gas
</td></tr>
<tr>
<td>7
</td>
<td>259
</td>
<td align="left"><a href="/wiki/Indian_Oil_Corporation" title="Indian Oil Corporation">Indian Oil Corporation</a>
</td>
<td align="left">New Delhi
</td>
<td>93.8
</td>
<td>5.0
</td>
<td>57.8
</td>
<td>27.8
</td>
<td align="left"><a href="/wiki/Petroleum_industry" title="Petroleum industry">Oil and gas</a>
</td></tr>
<tr>
<td>8
</td>
<td>284
</td>
<td align="left"><a href="/wiki/Tata_Motors" title="Tata Motors">Tata Motors</a>
</td>
<td align="left">Mumbai
</td>
<td>52.9
</td>
<td>3.8
</td>
<td>44.4
</td>
<td>43.8
</td>
<td align="left">Automotive
</td></tr>
<tr>
<td>9
</td>
<td>293
</td>
<td align="left"><a href="/wiki/Axis_Bank" title="Axis Bank">Axis Bank</a>
</td>
<td align="left">Mumbai
</td>
<td>16.7
</td>
<td>3.2
</td>
<td>182.0
</td>
<td>42.3
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>10
</td>
<td>372
</td>
<td align="left"><a href="/wiki/NTPC_Limited" title="NTPC Limited">NTPC Limited</a>
</td>
<td align="left">New Delhi
</td>
<td>21.2
</td>
<td>2.4
</td>
<td>54.7
</td>
<td>42.5
</td>
<td align="left">Utilities
</td></tr>
<tr>
<td>11
</td>
<td>398
</td>
<td align="left"><a href="/wiki/Larsen_%26_Toubro" title="Larsen &amp; Toubro">Larsen &amp; Toubro</a>
</td>
<td align="left">Mumbai
</td>
<td>26.7
</td>
<td>1.6
</td>
<td>40.7
</td>
<td>56.9
</td>
<td align="left">Capital goods
</td></tr>
<tr>
<td>12
</td>
<td>412
</td>
<td align="left"><a href="/wiki/Tata_Consultancy_Services" title="Tata Consultancy Services">Tata Consultancy Services</a>
</td>
<td align="left">Mumbai
</td>
<td>29.1
</td>
<td>5.5
</td>
<td>17.6
</td>
<td>166.5
</td>
<td align="left">Infotech
</td></tr>
<tr>
<td>13
</td>
<td>440
</td>
<td align="left"><a href="/wiki/Bank_of_Baroda" title="Bank of Baroda">Bank of Baroda</a>
</td>
<td align="left">Vadodara
</td>
<td>17.1
</td>
<td>2.3
</td>
<td>198.4
</td>
<td>16.2
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>14
</td>
<td>442
</td>
<td align="left"><a href="/wiki/Kotak_Mahindra_Bank" title="Kotak Mahindra Bank">Kotak Mahindra Bank</a>
</td>
<td align="left">Mumbai
</td>
<td>11.4
</td>
<td>2.2
</td>
<td>92.0
</td>
<td>40.5
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>15
</td>
<td>472
</td>
<td align="left"><a href="/wiki/Bharti_Airtel" title="Bharti Airtel">Bharti Airtel</a>
</td>
<td align="left">New Delhi
</td>
<td>18.1
</td>
<td>0.9
</td>
<td>53.3
</td>
<td>91.5
</td>
<td align="left">Telecommunication
</td></tr>
<tr>
<td>16
</td>
<td>488
</td>
<td align="left"><a href="/wiki/Coal_India" title="Coal India">Coal India</a>
</td>
<td align="left">Kolkata
</td>
<td>17.2
</td>
<td>3.9
</td>
<td>28.5
</td>
<td>34.8
</td>
<td align="left">Metals and mining
</td></tr>
<tr>
<td>17
</td>
<td>525
</td>
<td align="left"><a href="/wiki/Canara_Bank" title="Canara Bank">Canara Bank</a>
</td>
<td align="left">Bangalore
</td>
<td>16.8
</td>
<td>1.8
</td>
<td>184.0
</td>
<td>12.4
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>18
</td>
<td>533
</td>
<td align="left"><a href="/wiki/Power_Finance_Corporation" title="Power Finance Corporation">Power Finance Corporation</a>
</td>
<td align="left">New Delhi
</td>
<td>11.1
</td>
<td>2.4
</td>
<td>124.6
</td>
<td>18.5
</td>
<td align="left">Financials
</td></tr>
<tr>
<td>19
</td>
<td>537
</td>
<td align="left"><a href="/wiki/Bharat_Petroleum" title="Bharat Petroleum">Bharat Petroleum</a>
</td>
<td align="left">Mumbai
</td>
<td>54.1
</td>
<td>3.2
</td>
<td>24.3
</td>
<td>16.4
</td>
<td align="left">Oil and gas
</td></tr>
<tr>
<td>20
</td>
<td>569
</td>
<td align="left"><a href="/wiki/Infosys" title="Infosys">Infosys</a>
</td>
<td align="left">Bangalore
</td>
<td>18.6
</td>
<td>3.2
</td>
<td>16.5
</td>
<td>71.9
</td>
<td align="left">Infotech
</td></tr>
<tr>
<td>21
</td>
<td>571
</td>
<td align="left"><a href="/wiki/Punjab_National_Bank" title="Punjab National Bank">Punjab National Bank</a>
</td>
<td align="left">New Delhi
</td>
<td>14.8
</td>
<td>1.1
</td>
<td>191.7
</td>
<td>16.5
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>22
</td>
<td>575
</td>
<td align="left"><a href="/wiki/Union_Bank_of_India" title="Union Bank of India">Union Bank of India</a>
</td>
<td align="left">Mumbai
</td>
<td>14.3
</td>
<td>1.7
</td>
<td>168.1
</td>
<td>12.7
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>23
</td>
<td>592
</td>
<td align="left"><a href="/wiki/Bajaj_Finserv" title="Bajaj Finserv">Bajaj Finserv</a>
</td>
<td align="left">Pune
</td>
<td>13.0
</td>
<td>1.0
</td>
<td>64.5
</td>
<td>30.3
</td>
<td align="left">Financials
</td></tr>
<tr>
<td>24
</td>
<td>593
</td>
<td align="left"><a href="/wiki/Mahindra_%26_Mahindra" title="Mahindra &amp; Mahindra">Mahindra &amp; Mahindra</a>
</td>
<td align="left">Mumbai
</td>
<td>16.8
</td>
<td>1.4
</td>
<td>28.3
</td>
<td>37.5
</td>
<td align="left">Automotive
</td></tr>
<tr>
<td>25
</td>
<td>645
</td>
<td align="left"><a class="mw-redirect" href="/wiki/JSW_Steel_Ltd" title="JSW Steel Ltd">JSW Steel Ltd</a>
</td>
<td align="left">Mumbai
</td>
<td>21.1
</td>
<td>1.1
</td>
<td>27.4
</td>
<td>26.6
</td>
<td align="left">Iron and steel
</td></tr>
<tr>
<td>26
</td>
<td>684
</td>
<td align="left"><a href="/wiki/Hindalco_Industries" title="Hindalco Industries">Hindalco Industries</a>
</td>
<td align="left">Mumbai
</td>
<td>26.1
</td>
<td>1.1
</td>
<td>27.1
</td>
<td>17.7
</td>
<td align="left">Metals and mining
</td></tr>
<tr>
<td>27
</td>
<td>746
</td>
<td align="left"><a href="/wiki/Grasim_Industries" title="Grasim Industries">Grasim Industries</a>
</td>
<td align="left">Mumbai
</td>
<td>15.3
</td>
<td>0.7
</td>
<td>47.0
</td>
<td>19.8
</td>
<td align="left">Diversified
</td></tr>
<tr>
<td>28
</td>
<td>764
</td>
<td align="left"><a class="mw-redirect" href="/wiki/HCL_Technologies" title="HCL Technologies">HCL Technologies</a>
</td>
<td align="left">Noida
</td>
<td>13.3
</td>
<td>1.9
</td>
<td>12.0
</td>
<td>43.4
</td>
<td align="left">Infotech
</td></tr>
<tr>
<td>29
</td>
<td>810
</td>
<td align="left"><a href="/wiki/ITC_Limited" title="ITC Limited">ITC Limited</a>
</td>
<td align="left">Kolkata
</td>
<td>8.5
</td>
<td>2.5
</td>
<td>10.5
</td>
<td>65.4
</td>
<td align="left">Consumer Goods
</td></tr>
<tr>
<td>30
</td>
<td>827
</td>
<td align="left"><a href="/wiki/Power_Grid_Corporation_of_India" title="Power Grid Corporation of India">Power Grid Corporation of India</a>
</td>
<td align="left">Gurgaon
</td>
<td>5.6
</td>
<td>1.9
</td>
<td>29.6
</td>
<td>35.0
</td>
<td align="left">Utilities
</td></tr>
<tr>
<td>31
</td>
<td>834
</td>
<td align="left"><a href="/wiki/Tata_Steel" title="Tata Steel">Tata Steel</a>
</td>
<td align="left">Kolkata
</td>
<td>28.3
</td>
<td>−0.4
</td>
<td>32.7
</td>
<td>25.1
</td>
<td align="left">Iron and steel
</td></tr>
<tr>
<td>32
</td>
<td>901
</td>
<td align="left"><a href="/wiki/IndusInd_Bank" title="IndusInd Bank">IndusInd Bank</a>
</td>
<td align="left">Mumbai
</td>
<td>6.7
</td>
<td>1.1
</td>
<td>61.8
</td>
<td>13.2
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>33
</td>
<td>922
</td>
<td align="left"><a href="/wiki/Indian_Railway_Finance_Corporation" title="Indian Railway Finance Corporation">Indian Railway Finance Corporation</a>
</td>
<td align="left">New Delhi
</td>
<td>3.2
</td>
<td>0.7
</td>
<td>58.6
</td>
<td>26.5
</td>
<td align="left">Financials
</td></tr>
<tr>
<td>34
</td>
<td>926
</td>
<td align="left"><a href="/wiki/Wipro" title="Wipro">Wipro</a>
</td>
<td align="left">Bangalore
</td>
<td>10.8
</td>
<td>1.3
</td>
<td>13.8
</td>
<td>28.9
</td>
<td align="left">Infotech
</td></tr>
<tr>
<td>35
</td>
<td>930
</td>
<td align="left"><a href="/wiki/GAIL" title="GAIL">GAIL</a>
</td>
<td align="left">New Delhi
</td>
<td>16.1
</td>
<td>1.2
</td>
<td>15.0
</td>
<td>16.1
</td>
<td align="left">Oil and gas
</td></tr>
<tr>
<td>36
</td>
<td>947
</td>
<td align="left"><a href="/wiki/Indian_Bank" title="Indian Bank">Indian Bank</a>
</td>
<td align="left">Chennai
</td>
<td>7.8
</td>
<td>1.0
</td>
<td>95.4
</td>
<td>8.7
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>37
</td>
<td>961
</td>
<td align="left"><a href="/wiki/Vedanta_Limited" title="Vedanta Limited">Vedanta Limited</a>
</td>
<td align="left">Mumbai
</td>
<td>17.4
</td>
<td>0.5
</td>
<td>22.9
</td>
<td>19.7
</td>
<td align="left">Metals and mining
</td></tr>
<tr>
<td>38
</td>
<td>1048
</td>
<td align="left"><a href="/wiki/Adani_Power" title="Adani Power">Adani Power</a>
</td>
<td align="left"><a href="/wiki/Ahmedabad" title="Ahmedabad">Ahmedabad</a>
</td>
<td>6.1
</td>
<td>2.5
</td>
<td>11.1
</td>
<td>29.4
</td>
<td align="left"><a href="/wiki/Energy" title="Energy">Energy</a>
</td></tr>
<tr>
<td>39
</td>
<td>1053
</td>
<td align="left"><a href="/wiki/Bank_of_India" title="Bank of India">Bank of India</a>
</td>
<td align="left">Mumbai
</td>
<td>8.1
</td>
<td>0.8
</td>
<td>110.8
</td>
<td>6.7
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>40
</td>
<td>1059
</td>
<td align="left"><a href="/wiki/Adani_Enterprises" title="Adani Enterprises">Adani Enterprises</a>
</td>
<td align="left">Ahmedabad
</td>
<td>12.7
</td>
<td>0.4
</td>
<td>19.3
</td>
<td>41.9
</td>
<td align="left">Holding
</td></tr>
<tr>
<td>41
</td>
<td>1161
</td>
<td align="left"><a class="mw-redirect" href="/wiki/Sun_Pharmaceutical" title="Sun Pharmaceutical">Sun Pharmaceutical</a>
</td>
<td align="left">Mumbai
</td>
<td>5.7
</td>
<td>1.1
</td>
<td>9.6
</td>
<td>44.1
</td>
<td align="left"><a href="/wiki/Pharmaceutical_industry" title="Pharmaceutical industry">Pharmaceuticals</a>
</td></tr>
<tr>
<td>42
</td>
<td>1212
</td>
<td align="left"><a href="/wiki/IndiGo" title="IndiGo">IndiGo</a>
</td>
<td align="left">Gurgaon
</td>
<td>7.9
</td>
<td>0.9
</td>
<td>8.8
</td>
<td>20.2
</td>
<td align="left"><a href="/wiki/Airline" title="Airline">Airline</a>
</td></tr>
<tr>
<td>43
</td>
<td>1219
</td>
<td align="left"><a href="/wiki/Adani_Ports_%26_SEZ" title="Adani Ports &amp; SEZ">Adani Ports &amp; SEZ</a>
</td>
<td align="left">Ahmedabad
</td>
<td>3.2
</td>
<td>1.0
</td>
<td>14.3
</td>
<td>34.6
</td>
<td align="left"><a class="mw-redirect" href="/wiki/Shipping" title="Shipping">Shipping</a>
</td></tr>
<tr>
<td>44
</td>
<td>1259
</td>
<td align="left"><a href="/wiki/IDBI_Bank" title="IDBI Bank">IDBI Bank</a>
</td>
<td align="left">Mumbai
</td>
<td>3.7
</td>
<td>0.7
</td>
<td>43.7
</td>
<td>10.9
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>45
</td>
<td>1264
</td>
<td align="left"><a href="/wiki/Bajaj_Auto" title="Bajaj Auto">Bajaj Auto</a>
</td>
<td align="left">Pune
</td>
<td>5.4
</td>
<td>0.9
</td>
<td>4.7
</td>
<td>29.4
</td>
<td align="left">Automotive
</td></tr>
<tr>
<td>46
</td>
<td>1281
</td>
<td align="left"><a class="mw-redirect" href="/wiki/Shriram_Transport_Finance" title="Shriram Transport Finance">Shriram Transport Finance</a>
</td>
<td align="left">Chennai
</td>
<td>4.4
</td>
<td>0.9
</td>
<td>29.8
</td>
<td>10.7
</td>
<td align="left">Financials
</td></tr>
<tr>
<td>47
</td>
<td>1384
</td>
<td align="left"><a href="/wiki/Asian_Paints" title="Asian Paints">Asian Paints</a>
</td>
<td align="left">Mumbai
</td>
<td>4.3
</td>
<td>0.7
</td>
<td>3.6
</td>
<td>32.3
</td>
<td align="left"><a href="/wiki/Chemical_industry" title="Chemical industry">Chemicals</a>
</td></tr>
<tr>
<td>48
</td>
<td>1534
</td>
<td align="left"><a href="/wiki/Tata_Power" title="Tata Power">Tata Power</a>
</td>
<td align="left">Mumbai
</td>
<td>7.4
</td>
<td>0.5
</td>
<td>16.7
</td>
<td>16.7
</td>
<td align="left">Utilities
</td></tr>
<tr>
<td>49
</td>
<td>1562
</td>
<td align="left"><a href="/wiki/Titan_Company" title="Titan Company">Titan Company</a>
</td>
<td align="left">Bangalore
</td>
<td>6.2
</td>
<td>0.0
</td>
<td>2.3
</td>
<td>1.1
</td>
<td align="left"><a href="/wiki/Jewellery" title="Jewellery">Gems and jewellery</a>
</td></tr>
<tr>
<td>50
</td>
<td>1604
</td>
<td align="left"><a href="/wiki/Jio_Financial_Services" title="Jio Financial Services">Jio Financial Services</a>
</td>
<td align="left">Mumbai
</td>
<td>0.2
</td>
<td>0.2
</td>
<td>17.4
</td>
<td>27.2
</td>
<td align="left">Financials
</td></tr>
<tr>
<td>49
</td>
<td>1568
</td>
<td align="left"><a href="/wiki/Rajesh_Exports" title="Rajesh Exports">Rajesh Exports</a>
</td>
<td align="left">Bangalore
</td>
<td>32.6
</td>
<td>0.1
</td>
<td>4.1
</td>
<td>2.0
</td>
<td align="left"><a href="/wiki/Jewellery" title="Jewellery">Gems and jewellery</a>
</td></tr>
<tr>
<td>50
</td>
<td>1617
</td>
<td align="left"><a href="/wiki/DMart" title="DMart">DMart</a>
</td>
<td align="left">Mumbai
</td>
<td>6.1
</td>
<td>0.3
</td>
<td>2.5
</td>
<td>36.6
</td>
<td align="left">Retail
</td></tr>
<tr>
<td>51
</td>
<td>1693
</td>
<td align="left"><a href="/wiki/Jindal_Steel_and_Power" title="Jindal Steel and Power">Jindal Steel and Power</a>
</td>
<td align="left">New Delhi
</td>
<td>6.0
</td>
<td>0.6
</td>
<td>9.4
</td>
<td>12.4
</td>
<td align="left">Iron and steel
</td></tr>
<tr>
<td>52
</td>
<td>1697
</td>
<td align="left"><a href="/wiki/LIC_Housing_Finance" title="LIC Housing Finance">LIC Housing Finance</a>
</td>
<td align="left">Mumbai
</td>
<td>3.3
</td>
<td>0.4
</td>
<td>34.9
</td>
<td>4.3
</td>
<td align="left">Financials
</td></tr>
<tr>
<td>53
</td>
<td>1699
</td>
<td align="left"><a href="/wiki/Adani_Green_Energy" title="Adani Green Energy">Adani Green Energy</a>
</td>
<td align="left">Ahmedabad
</td>
<td>1.1
</td>
<td>0.1
</td>
<td>10.6
</td>
<td>34.8
</td>
<td align="left"><a href="/wiki/Renewable_energy" title="Renewable energy">Renewable energy</a>
</td></tr>
<tr>
<td>54
</td>
<td>1704
</td>
<td align="left"><a href="/wiki/Bajaj_Group" title="Bajaj Group">Bajaj Holdings &amp; Investment</a>
</td>
<td align="left">Mumbai
</td>
<td>0.2
</td>
<td>0.9
</td>
<td>7.8
</td>
<td>11.0
</td>
<td align="left">Holding
</td></tr>
<tr>
<td>55
</td>
<td>1760
</td>
<td align="left"><a href="/wiki/General_Insurance_Corporation_of_India" title="General Insurance Corporation of India">General Insurance Corporation</a>
</td>
<td align="left">Mumbai
</td>
<td>5.7
</td>
<td>0.9
</td>
<td>20.9
</td>
<td>7.2
</td>
<td align="left">Insurance
</td></tr>
<tr>
<td>56
</td>
<td>1769
</td>
<td align="left"><a href="/wiki/Yes_Bank" title="Yes Bank">Yes Bank</a>
</td>
<td align="left">Mumbai
</td>
<td>4.0
</td>
<td>0.2
</td>
<td>48.7
</td>
<td>8.3
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>57
</td>
<td>1805
</td>
<td align="left"><a class="mw-redirect" href="/wiki/Motherson_Sumi_Systems" title="Motherson Sumi Systems">Motherson Sumi Systems</a>
</td>
<td align="left"><a href="/wiki/Noida" title="Noida">Noida</a>
</td>
<td>11.4
</td>
<td>0.2
</td>
<td>9.4
</td>
<td>10.5
</td>
<td align="left">Automotive
</td></tr>
<tr>
<td>58
</td>
<td>1821
</td>
<td align="left"><a href="/wiki/Bharat_Electronics" title="Bharat Electronics">Bharat Electronics</a>
</td>
<td align="left">Bangalore
</td>
<td>2.2
</td>
<td>0.4
</td>
<td>4.4
</td>
<td>21.8
</td>
<td align="left"><a href="/wiki/Aerospace_engineering" title="Aerospace engineering">Aerospace</a> and <a href="/wiki/Arms_industry" title="Arms industry">defense</a>
</td></tr>
<tr>
<td>59
</td>
<td>1840
</td>
<td align="left"><a href="/wiki/Central_Bank_of_India" title="Central Bank of India">Central Bank of India</a>
</td>
<td align="left">Mumbai
</td>
<td>4.3
</td>
<td>0.3
</td>
<td>53.7
</td>
<td>6.4
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>60
</td>
<td>1842
</td>
<td align="left">Bank of Maharashtra
</td>
<td align="left">Pune
</td>
<td>2.8
</td>
<td>0.5
</td>
<td>36.8
</td>
<td>5.5
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>61
</td>
<td>1848
</td>
<td align="left"><a href="/wiki/Indus_Towers" title="Indus Towers">Indus Towers</a>
</td>
<td align="left">Gurgaon
</td>
<td>3.5
</td>
<td>0.7
</td>
<td>6.7
</td>
<td>11.1
</td>
<td align="left">Telecommunication
</td></tr>
<tr>
<td>62
</td>
<td>1853
</td>
<td align="left"><a class="mw-redirect" href="/wiki/Steel_Authority_of_India" title="Steel Authority of India">Steel Authority of India</a>
</td>
<td align="left">New Delhi
</td>
<td>12.9
</td>
<td>0.4
</td>
<td>15.6
</td>
<td>8.3
</td>
<td align="left">Iron and steel
</td></tr>
<tr>
<td>63
</td>
<td>1869
</td>
<td align="left"><a href="/wiki/Federal_Bank" title="Federal Bank">Federal Bank</a>
</td>
<td align="left"><a href="/wiki/Kochi" title="Kochi">Kochi</a>
</td>
<td>3.2
</td>
<td>0.5
</td>
<td>38.1
</td>
<td>4.8
</td>
<td align="left">Banking
</td></tr>
<tr>
<td>64
</td>
<td>1873
</td>
<td align="left"><a href="/wiki/DLF_(company)" title="DLF (company)">DLF</a>
</td>
<td align="left">Gurgaon
</td>
<td>0.8
</td>
<td>0.3
</td>
<td>7.2
</td>
<td>25.2
</td>
<td align="left"><a href="/wiki/Real_estate" title="Real estate">Real estate</a>
</td></tr>
<tr>
<td>65
</td>
<td>1895
</td>
<td align="left"><a href="/wiki/Dr._Reddy%27s_Laboratories" title="Dr. Reddy's Laboratories">Dr. Reddy's Laboratories</a>
</td>
<td align="left"><a href="/wiki/Hyderabad" title="Hyderabad">Hyderabad</a>
</td>
<td>3.4
</td>
<td>0.7
</td>
<td>4.6
</td>
<td>11.6
</td>
<td align="left"><a href="/wiki/Pharmaceutical_industry" title="Pharmaceutical industry">Pharmaceuticals</a>
</td></tr>
<tr>
<td>66
</td>
<td>1908
</td>
<td align="left"><a href="/wiki/Varun_Beverages" title="Varun Beverages">Varun Beverages</a>
</td>
<td align="left">Gurgaon
</td>
<td>2.0
</td>
<td>0.3
</td>
<td>1.8
</td>
<td>23.6
</td>
<td align="left">Beverages
</td></tr>
<tr>
<td>67
</td>
<td>1949
</td>
<td align="left"><a href="/wiki/Cholamandalam_Investment_and_Finance_Company" title="Cholamandalam Investment and Finance Company">CIFCL</a>
</td>
<td align="left">Chennai
</td>
<td>2.3
</td>
<td>0.4
</td>
<td>18.8
</td>
<td>13.0
</td>
<td align="left">Financials
</td></tr>
<tr>
<td>68
</td>
<td>1957
</td>
<td align="left"><a href="/wiki/National_Mineral_Development_Corporation" title="National Mineral Development Corporation">NMDC</a>
</td>

In [2]:
# soup.find_all('table')[1]

In [3]:
# soup.find('table', class_='wikitable sortable')

In [9]:
table = soup.find_all('table')[1]

In [4]:
# print(table)

In [10]:
table.find_all('th')

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Industry
 </th>,
 <th>Revenue<br/><small>(in  <b>₹ Crore</b>)</small>
 </th>,
 <th>Revenue growth
 </th>,
 <th>Profits<br/><small>(in  <b>₹ Crore</b>)</small>
 </th>,
 <th>Headquarters
 </th>,
 <th><a href="/wiki/List_of_public_sector_undertakings_in_India" title="List of public sector undertakings in India">State Controlled</a>
 </th>]

In [13]:
world_titles = table.find_all('th')

In [15]:
world_table_titles = [title.text.strip() for title in world_titles]
print(world_table_titles)

['Rank', 'Name', 'Industry', 'Revenue(in  ₹ Crore)', 'Revenue growth', 'Profits(in  ₹ Crore)', 'Headquarters', 'State Controlled']

In [16]:
import pandas as pd

In [18]:
df = pd.DataFrame(columns = world_table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue(in  ₹ Crore), Revenue growth, Profits(in  ₹ Crore), Headquarters, State Controlled]
Index: []

In [24]:
column_data = table.find_all('tr')

In [31]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_rdata = [data.text.strip() for data in row_data]
    
    # print(individual_rdata)

    length = len(df)
    df.loc[length] = individual_rdata

In [32]:
df

,Rank,Name,Industry,Revenue(in ₹ Crore),Revenue growth,Profits(in ₹ Crore),Headquarters,State Controlled
0,1,Reliance Industries Limited,Oil and gas,"920,274",25%,"66,702",Mumbai,
1,2,Indian Oil Corporation,Oil and gas,"872,093",25%,"9,792",New Delhi,Yes
2,3,Life Insurance Corporation,Insurance,"792,427",9%,"35,997",Mumbai,Yes
3,4,Oil and Natural Gas Corporation,Oil and gas,"638,965",27%,"35,440",New Delhi,Yes
4,5,Bharat Petroleum,Oil and gas,"477,855",34%,"2,131",Mumbai,Yes
5,6,State Bank of India,Banking,"473,378",16%,"55,648",Mumbai,Yes
6,7,Tata Motors,Automotive,"357,317",28%,"2,414",Mumbai,
7,8,Tata Steel,Iron and steel,"248,374",2%,"8,760",Mumbai,
8,9,Tata Consultancy Services,Infotech,"228,907",17%,"42,147",Mumbai,
9,10,Hindalco Industries,Metals and mining,"221,268",7%,"10,097",Mumbai,
10,11,HDFC Bank,Banking,"204,666",22%,"45,997",Mumbai,
11,12,Larsen & Toubro,Capital goods,"189,563",18%,"10,471",Mumbai,
12,13,ICICI Bank,Banking,"186,179",18%,"34,037",Mumbai,
13,14,NTPC Limited,Utilities,"178,906",30.0%,"16,913",New Delhi,Yes
14,15,JSW Steel Ltd,Iron and steel,"170,217",12%,"4,144",Mumbai,
15,16,HDFC,Financials,"164,163",13%,"26,161",Mumbai,
16,17,Vedanta Resources,Metals and mining,"151,289",8%,"10,574","London, UK",
17,18,GAIL,Oil and gas,"150,505",57%,"5,616",New Delhi,Yes
18,19,Infosys,Infotech,"145,481",21%,"28,165",Bangalore,
19,20,Coal India,Metals and mining,"145,481",31%,"28,165",Kolkata,Yes
20,21,Bharti Airtel,Telecommunication,"140,834",15%,"8,346",New Delhi,
21,22,Mahindra & Mahindra,Automotive,"129,004",37%,"10,282",Mumbai,
22,23,Grasim Industries,Diversified,"122,283",24%,"6,827",Mumbai,
23,24,Maruti Suzuki India,Automotive,"120,293",33%,"8,211",New Delhi,
24,25,Nayara Energy,Oil and gas,"116,240",19%,"9,426",Mumbai,
25,26,Steel Authority of India,Iron and steel,"111,501",6%,"2,177",New Delhi,Yes
26,27,Canara Bank,Banking,"111,210",18%,"11,255",Bangalore,Yes
27,28,Bank of Baroda,Banking,"110,778",26%,"14,905",Vadodara,Yes
28,29,Axis Bank,Banking,"106,155",23%,"10,818",Mumbai,Yes
29,30,HCL Technologies,Infotech,"102,881",19%,"14,851",Noida,
30,31,Punjab National Bank,Banking,"99,374",12%,"3,348",New Delhi,Yes
31,32,Union Bank of India,Banking,"97,079",19%,"8,512",Mumbai,Yes
32,33,Wipro,Infotech,"92,738",14%,"11,350",Bangalore,
33,34,Uttar Pradesh Power Corporation,Utilities,"90,272",12%,"−15,859",Lucknow,Yes
34,35,Bajaj Finserv,Financials,"82,073",20%,"6,417",Pune,
35,36,Motherson Sumi Systems,Automotive,"79,281",23%,"1,496",Noida,
36,37,Power Finance Corporation,Financial services,"77,625",2%,"15,889",New Delhi,Yes
37,38,ITC Limited,Consumer goods,"73,398",16%,"19,192",Kolkata,
38,39,Kotak Mahindra Bank,Banking,"68,142",16%,"14,925",Mumbai,
39,40,IFFCO,Agriculture,"63,386",46%,"3,053",New Delhi,Yes
40,41,Hyundai Motor India,Automotive,"61,572",28%,"4,709",Gurgaon,
41,42,Hindustan Unilever,Consumer goods,"61,342",16%,"10,120",Mumbai,
42,43,Tata Power,Utilities,"61,080",32%,"3,336",Mumbai,
43,44,Petronet LNG,Oil and gas,"60,560",39%,"3,326",New Delhi,Yes
44,45,IndiGo,Airline,"55,883",110%,−306,Gurgaon,
45,46,Bank of India,Banking,"55,100",19%,"3,838",Mumbai,Yes
46,47,Adani Wilmar,Food processing,"54,471",1%,582,Ahmedabad,
47,48,Tech Mahindra,Infotech,"54,255",19%,"4,831",Pune,
48,49,UPL,Chemicals,"54,210",16%,"3,570",Mumbai,
49,50,Jindal Steel and Power,Iron and steel,"54,194",4%,"3,174",New Delhi,

In [37]:
df.to_csv(r'D:\localdiskshort\jupyterfiles\companies.csv', index = False)

  Rank                             Name     Industry Revenue(in  ₹ Crore)  \
0    1      Reliance Industries Limited  Oil and gas              920,274
1    2           Indian Oil Corporation  Oil and gas              872,093
2    3       Life Insurance Corporation    Insurance              792,427
3    4  Oil and Natural Gas Corporation  Oil and gas              638,965
4    5                 Bharat Petroleum  Oil and gas              477,855

  Revenue growth Profits(in  ₹ Crore) Headquarters State Controlled
0            25%               66,702       Mumbai
1            25%                9,792    New Delhi              Yes
2             9%               35,997       Mumbai              Yes
3            27%               35,440    New Delhi              Yes
4            34%                2,131       Mumbai              Yes